# Generated by Django 5.1.2 on 2024-10-27 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='timestamp',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='message',
            name='read',
        ),
        migrations.AlterField(
            model_name='message',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
